api:
  # Do not use trailing spaces for the baseUrl
  baseUrl: https://frozen-taiga-40327.herokuapp.com:3000
  host: 127.0.0.1
  port: 3000
  version: api/v1

admin:
  url: https://frozen-taiga-40327.herokuapp.com:9000
  recoverPath: /#/password-reset

colmena:
  modules:
    '@colmena/module-api-content': true
    '@colmena/module-api-core': true
    '@colmena/module-api-storage': true
    '@colmena/module-api-system': true

hideBootWarning: false

mongodb:
  url: mongodb://localhost/colmena-dev


settings:
  registrationEnabled: true

smtp:
  host: localhost
  port: 102

storage:
  path: './storage'

system:
  initdb: true
  migratedb: false
