api:
  # Do not use trailing spaces for the baseUrl
  baseUrl: http://35.247.174.245:3000
  host: 35.247.174.245
  port: 3000
  version: api/v1

admin:
  url: http://35.247.174.245:9000
  recoverPath: /#/password-reset

colmena:
  modules:
    '@colmena/module-api-content': true
    '@colmena/module-api-core': true
    '@colmena/module-api-storage': true
    '@colmena/module-api-system': true

hideBootWarning: false

mongodb:
  url: mongodb://admin:ojAQSWXQRPT6slk6@cluster0-shard-00-00-qezsn.mongodb.net:27017,cluster0-shard-00-01-qezsn.mongodb.net:27017,cluster0-shard-00-02-qezsn.mongodb.net:27017/cms?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true

settings:
  registrationEnabled: true

smtp:
  host: false
  port: false

storage:
  path: './storage'

system:
  initdb: false
  migratedb: false
